wget http://useast.ensembl.org/i/species/Orycteropus_afer_afer.png
wget http://useast.ensembl.org/i/species/Mus_spretus.png
wget http://useast.ensembl.org/i/species/Vicugna_pacos.png
wget http://useast.ensembl.org/i/species/Poecilia_formosa.png
wget http://useast.ensembl.org/i/species/Colobus_angolensis_palliatus.png
wget http://useast.ensembl.org/i/species/Anolis_carolinensis.png
wget http://useast.ensembl.org/i/species/Dasypus_novemcinctus.png
wget http://useast.ensembl.org/i/species/Rhinopithecus_bieti.png
wget http://useast.ensembl.org/i/species/Saimiri_boliviensis_boliviensis.png
wget http://useast.ensembl.org/i/species/Pan_paniscus.png
wget http://useast.ensembl.org/i/species/Cavia_aperea.png
wget http://useast.ensembl.org/i/species/Melopsittacus_undulatus.png
wget http://useast.ensembl.org/i/species/Otolemur_garnettii.png
wget http://useast.ensembl.org/i/species/Ciona_intestinalis.png
wget http://useast.ensembl.org/i/species/Ciona_savignyi.png
wget http://useast.ensembl.org/i/species/Caenorhabditis_elegans.png
wget http://useast.ensembl.org/i/species/Cebus_capucinus.png
wget http://useast.ensembl.org/i/species/Felis_catus.png
wget http://useast.ensembl.org/i/species/Astyanax_mexicanus.png
wget http://useast.ensembl.org/i/species/Gallus_gallus.png
wget http://useast.ensembl.org/i/species/Pan_troglodytes.png
wget http://useast.ensembl.org/i/species/Cricetulus_griseus_chok1gshd.png
wget http://useast.ensembl.org/i/species/Cricetulus_griseus_crigri.png
wget http://useast.ensembl.org/i/species/Pelodiscus_sinensis.png
wget http://useast.ensembl.org/i/species/Gadus_morhua.png
wget http://useast.ensembl.org/i/species/Latimeria_chalumnae.png
wget http://useast.ensembl.org/i/species/Propithecus_coquereli.png
wget http://useast.ensembl.org/i/species/Bos_taurus.png
wget http://useast.ensembl.org/i/species/Macaca_fascicularis.png
wget http://useast.ensembl.org/i/species/Fukomys_damarensis.png
wget http://useast.ensembl.org/i/species/Octodon_degus.png
wget http://useast.ensembl.org/i/species/Canis_familiaris.png
wget http://useast.ensembl.org/i/species/Tursiops_truncatus.png
wget http://useast.ensembl.org/i/species/Mandrillus_leucophaeus.png
wget http://useast.ensembl.org/i/species/Anas_platyrhynchos.png
wget http://useast.ensembl.org/i/species/Loxodonta_africana.png
wget http://useast.ensembl.org/i/species/Mustela_putorius_furo.png
wget http://useast.ensembl.org/i/species/Ficedula_albicollis.png
wget http://useast.ensembl.org/i/species/Drosophila_melanogaster.png
wget http://useast.ensembl.org/i/species/Takifugu_rubripes.png
wget http://useast.ensembl.org/i/species/Nomascus_leucogenys.png
wget http://useast.ensembl.org/i/species/Capra_hircus.png
wget http://useast.ensembl.org/i/species/Mesocricetus_auratus.png
wget http://useast.ensembl.org/i/species/Rhinopithecus_roxellana.png
wget http://useast.ensembl.org/i/species/Gorilla_gorilla.png
wget http://useast.ensembl.org/i/species/Cavia_porcellus.png
wget http://useast.ensembl.org/i/species/Papio_hamadryas.png
wget http://useast.ensembl.org/i/species/Erinaceus_europaeus.png
wget http://useast.ensembl.org/i/species/Equus_caballus.png
wget http://useast.ensembl.org/i/species/Homo_sapiens.png
wget http://useast.ensembl.org/i/species/Procavia_capensis.png
wget http://useast.ensembl.org/i/species/Dipodomys_ordii.png
wget http://useast.ensembl.org/i/species/Petromyzon_marinus.png
wget http://useast.ensembl.org/i/species/Jaculus_jaculus.png
wget http://useast.ensembl.org/i/species/Echinops_telfairi.png
wget http://useast.ensembl.org/i/species/Chinchilla_lanigera.png
wget http://useast.ensembl.org/i/species/Aotus_nancymaae.png
wget http://useast.ensembl.org/i/species/Macaca_mulatta.png
wget http://useast.ensembl.org/i/species/Callithrix_jacchus.png
wget http://useast.ensembl.org/i/species/Oryzias_latipes.png
wget http://useast.ensembl.org/i/species/Pteropus_vampyrus.png
wget http://useast.ensembl.org/i/species/Myotis_lucifugus.png
wget http://useast.ensembl.org/i/species/Mus_musculus.png
wget http://useast.ensembl.org/i/species/Mus_musculus_129S1_SvImJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_A_J.png
wget http://useast.ensembl.org/i/species/Mus_musculus_AKR_J.png
wget http://useast.ensembl.org/i/species/Mus_musculus_BALB_cJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_C3H_HeJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_C57BL_6NJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_CAST_EiJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_CBA_J.png
wget http://useast.ensembl.org/i/species/Mus_musculus_DBA_2J.png
wget http://useast.ensembl.org/i/species/Mus_musculus_FVB_NJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_LP_J.png
wget http://useast.ensembl.org/i/species/Microcebus_murinus.png
wget http://useast.ensembl.org/i/species/Mus_musculus_NOD_ShiLtJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_NZO_HlLtJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_PWK_PhJ.png
wget http://useast.ensembl.org/i/species/Mus_musculus_WSB_EiJ.png
wget http://useast.ensembl.org/i/species/Heterocephalus_glaber_female.png
wget http://useast.ensembl.org/i/species/Heterocephalus_glaber_male.png
wget http://useast.ensembl.org/i/species/Peromyscus_maniculatus_bairdii.png
wget http://useast.ensembl.org/i/species/Papio_anubis.png
wget http://useast.ensembl.org/i/species/Monodelphis_domestica.png
wget http://useast.ensembl.org/i/species/Pongo_abelii.png
wget http://useast.ensembl.org/i/species/Chrysemys_picta_bellii.png
wget http://useast.ensembl.org/i/species/Ailuropoda_melanoleuca.png
wget http://useast.ensembl.org/i/species/Sus_scrofa.png
wget http://useast.ensembl.org/i/species/Sus_scrofa_map.png
wget http://useast.ensembl.org/i/species/Macaca_nemestrina.png
wget http://useast.ensembl.org/i/species/Ochotona_princeps.png
wget http://useast.ensembl.org/i/species/Xiphophorus_maculatus.png
wget http://useast.ensembl.org/i/species/Ornithorhynchus_anatinus.png
wget http://useast.ensembl.org/i/species/Microtus_ochrogaster.png
wget http://useast.ensembl.org/i/species/Oryctolagus_cuniculus.png
wget http://useast.ensembl.org/i/species/Rattus_norvegicus.png
wget http://useast.ensembl.org/i/species/Ceratotherium_simum_simum.png
wget http://useast.ensembl.org/i/species/Mus_caroli.png
wget http://useast.ensembl.org/i/species/Saccharomyces_cerevisiae.png
wget http://useast.ensembl.org/i/species/Ovis_aries.png
wget http://useast.ensembl.org/i/species/Sorex_araneus.png
wget http://useast.ensembl.org/i/species/Mus_pahari.png
wget http://useast.ensembl.org/i/species/Choloepus_hoffmanni.png
wget http://useast.ensembl.org/i/species/Cercocebus_atys.png
wget http://useast.ensembl.org/i/species/Physter_macrocephalus.png
wget http://useast.ensembl.org/i/species/Lepisosteus_oculatus.png
wget http://useast.ensembl.org/i/species/Ictidomys_tridecemlineatus.png
wget http://useast.ensembl.org/i/species/Gasterosteus_aculeatus.png
wget http://useast.ensembl.org/i/species/Carlito_syrichta.png
wget http://useast.ensembl.org/i/species/Sarcophilus_harrisii.png
wget http://useast.ensembl.org/i/species/Tetraodon_nigroviridis.png
wget http://useast.ensembl.org/i/species/Oreochromis_niloticus.png
wget http://useast.ensembl.org/i/species/Tupaia_belangeri.png
wget http://useast.ensembl.org/i/species/Meleagris_gallopavo.png
wget http://useast.ensembl.org/i/species/Nannospalax_galili.png
wget http://useast.ensembl.org/i/species/Chlorocebus_sabaeus.png
wget http://useast.ensembl.org/i/species/Notamacropus_eugenii.png
wget http://useast.ensembl.org/i/species/Xenopus_tropicalis.png
wget http://useast.ensembl.org/i/species/Taeniopygia_guttata.png
wget http://useast.ensembl.org/i/species/Danio_rerio.png
