DEBUG = True
SECRET_KEY = 'bQEiLmOFPxAOrkdt80AHrms0bwWTJyPdIknysusLzatsm0YnZwzIgWK4zvxBZAO9i'  # make sure to change this
MONGO_HOST = '127.0.0.1'
MONGO_AUTH_MECHANISM='SCRAM-SHA-1'
MONGO_PORT = 26906
MONGO_DBNAME = 'AnimalTFDB3'
MONGO_USERNAME = 'AnimalTFDB3_reader'
MONGO_PASSWORD = 'AnimalTFDB3_reader'
